[package]
name = "status-bar"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
simple_logger = "5"
gtk4 = "0.8"
gtk4-layer-shell = "0.3"
tokio = { version = "1.39", features = ["full"] }
bar = { path = "../bar" }
utils = { path = "../utils" }

[lints]
workspace = true
